[package]
name = "transcribe-whisper-local"
version = "0.1.0"
edition = "2024"

[features]
default = []
coreml = ["meeki-whisper-local/coreml"]
directml = ["meeki-pyannote-local/directml"]
cuda = ["meeki-whisper-local/cuda"]
hipblas = ["meeki-whisper-local/hipblas"]
openblas = ["meeki-whisper-local/openblas"]
metal = ["meeki-whisper-local/metal"]
vulkan = ["meeki-whisper-local/vulkan"]
openmp = ["meeki-whisper-local/openmp"]
[dev-dependencies]
bytes = { workspace = true }
dirs = { workspace = true }
futures-util = { workspace = true }
meeki-data = { workspace = true }
owhisper-client = { workspace = true }
reqwest = { workspace = true, features = ["json", "stream"] }
tokio-tungstenite = { workspace = true }

[dependencies]
meeki-audio-chunking = { workspace = true }
meeki-audio-interface = { workspace = true }
meeki-audio-utils = { workspace = true }
meeki-model-manager = { workspace = true, features = ["whisper-local"] }
meeki-pyannote-local = { workspace = true }
meeki-transcribe-core = { workspace = true }
meeki-whisper = { workspace = true }
meeki-whisper-local = { workspace = true }
meeki-ws-utils = { workspace = true }
owhisper-interface = { workspace = true }

bytes = { workspace = true }
serde_html_form = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }

axum = { workspace = true, features = ["ws"] }
futures-util = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }

rodio = { workspace = true }
