[package]
name = "local-llm-core"
version = "0.1.0"
edition = "2024"

[features]
specta = ["dep:specta"]

[dependencies]
meeki-file = { workspace = true }
meeki-gguf = { workspace = true }
meeki-lmstudio = { workspace = true }
meeki-local-model = { workspace = true }

dirs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process", "time", "macros", "rt"] }

specta = { workspace = true, optional = true }
