[package]
name = "api-messenger"
version = "0.1.0"
edition = "2024"

[dependencies]
meeki-api-error = { workspace = true }
meeki-http = { workspace = true }
meeki-slack-web = { workspace = true }
meeki-teems = { workspace = true }

axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
