[package]
name = "api-pyannote"
version = "0.1.0"
edition = "2024"

[dependencies]
meeki-api-auth = { workspace = true }
meeki-api-env = { workspace = true }
meeki-api-error = { workspace = true }
meeki-pyannote-cloud = { workspace = true }

axum = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true }
wiremock = { workspace = true }
