[package]
name = "audio-norm"
version = "0.1.0"
edition = "2024"

[dependencies]
audioadapter-buffers = "2.0"
meeki-afconvert = { workspace = true }
meeki-audio-utils = { workspace = true }
meeki-mp3 = { workspace = true }
meeki-resampler = { workspace = true }

rodio = { workspace = true, features = ["symphonia-all"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_fs = "1"
meeki-data = { workspace = true }
