[package]
name = "vad-masking"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
hound = { workspace = true }
meeki-audacity = { workspace = true }
meeki-data = { workspace = true }
rodio = { workspace = true }

[dependencies]
meeki-audio-utils = { workspace = true }
meeki-vad = { workspace = true, features = ["earshot"] }
