[package]
name = "api-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
meeki-api-error = { workspace = true }
meeki-api-nango = { workspace = true }
meeki-google-drive = { workspace = true }
meeki-nango = { workspace = true }

utoipa = { workspace = true }

axum = { workspace = true }
sentry = { workspace = true }
tracing = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
