[package]
name = "local-model"
version = "0.1.0"
edition = "2024"

[dependencies]
meeki-am = { workspace = true }
meeki-file = { workspace = true }
meeki-model-downloader = { workspace = true }
meeki-transcribe-soniqo = { workspace = true }
meeki-whisper-local-model = { workspace = true }

serde = { workspace = true }
specta = { workspace = true }
