[package]
name = "api-mail"
version = "0.1.0"
edition = "2024"

[dependencies]
meeki-api-auth = { workspace = true }
meeki-api-error = { workspace = true }
meeki-api-nango = { workspace = true }
meeki-google-mail = { workspace = true, features = ["utoipa"] }
meeki-nango = { workspace = true }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
